# Generated by Django 5.1.4 on 2025-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_musician_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
