# Generated by Django 5.1.4 on 2025-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_musician_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
