# Generated by Django 5.1.4 on 2025-01-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_musician_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
