# Generated by Django 5.1.4 on 2025-01-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tagpost_alter_musician_cat_musician_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('died', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='alive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alive', to='main.alive'),
        ),
    ]
