# Generated by Django 5.1.4 on 2025-01-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_died_alive_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='alive',
            name='pl_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
